name: room_booking_system
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=2.19.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  # cloud_firestore: ^3.15
  firebase_auth: ^4.5.0
  flutter_svg: ^2.0.5
  firebase_database: ^10.1.2
  firebase_core: ^2.11.0
  syncfusion_flutter_datagrid: ^21.2.10
  flutter_chat_ui: ^1.6.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  textfield_tags: ^2.0.2
  image_picker:

flutter:
  uses-material-design: true
  assets: 
    - assets/images/

fonts:
- family: Ubuntu

