// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD0NcWXqzjtnRFMlUUAUd87G8h2E5RVMHc',
    appId: '1:17721238167:web:fd6af48383e832fb34ffd2',
    messagingSenderId: '17721238167',
    projectId: 'excelcius-room-booking-system',
    authDomain: 'excelcius-room-booking-system.firebaseapp.com',
    databaseURL: 'https://excelcius-room-booking-system-default-rtdb.firebaseio.com',
    storageBucket: 'excelcius-room-booking-system.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCmAvCSnT64vDbpN7ji6wg5jG_vim_U0gk',
    appId: '1:17721238167:android:f8acf25cc8d51dd034ffd2',
    messagingSenderId: '17721238167',
    projectId: 'excelcius-room-booking-system',
    databaseURL: 'https://excelcius-room-booking-system-default-rtdb.firebaseio.com',
    storageBucket: 'excelcius-room-booking-system.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCptoUW9qdomiW3mipeJT45alAiRisdRbE',
    appId: '1:17721238167:ios:47eb4d9cba57055734ffd2',
    messagingSenderId: '17721238167',
    projectId: 'excelcius-room-booking-system',
    databaseURL: 'https://excelcius-room-booking-system-default-rtdb.firebaseio.com',
    storageBucket: 'excelcius-room-booking-system.appspot.com',
    iosClientId: '17721238167-fb3qo0lm3tdc2ejg26ojutn1pu1rb3po.apps.googleusercontent.com',
    iosBundleId: 'com.example.roomBookingSystem',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCptoUW9qdomiW3mipeJT45alAiRisdRbE',
    appId: '1:17721238167:ios:47eb4d9cba57055734ffd2',
    messagingSenderId: '17721238167',
    projectId: 'excelcius-room-booking-system',
    databaseURL: 'https://excelcius-room-booking-system-default-rtdb.firebaseio.com',
    storageBucket: 'excelcius-room-booking-system.appspot.com',
    iosClientId: '17721238167-fb3qo0lm3tdc2ejg26ojutn1pu1rb3po.apps.googleusercontent.com',
    iosBundleId: 'com.example.roomBookingSystem',
  );
}
